apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: taiga
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-async-rabbitmq-data
  name: taiga-async-rabbitmq-data
spec:
  storageClassName: storage-nfs-pv-async
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: taiga
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-db-data
  name: taiga-db-data
spec:
  storageClassName: storage-nfs-pv-taiga-db
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: taiga
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-events-rabbitmq-data
  name: taiga-events-rabbitmq-data
spec:
  storageClassName: storage-nfs-pv-events
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: taiga
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-gateway-claim0
  name: taiga-gateway-claim0
spec:
  storageClassName: storage-nfs-pv-gateway
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: taiga
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-media-data
  name: taiga-media-data
spec:
  storageClassName: storage-nfs-pv-back-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: taiga
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-static-data
  name: taiga-static-data
spec:
  storageClassName: storage-nfs-pv-back-static
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
