apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: taiga
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-front
  name: taiga-front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: taiga-front
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/taiga: "true"
        io.kompose.service: taiga-front
    spec:
      containers:
        - env:
            - name: TAIGA_SUBPATH
            - name: TAIGA_URL
              value: http://10.1.3.53
            - name: TAIGA_WEBSOCKETS_URL
              value: ws://10.1.3.53
          image: taigaio/taiga-front:latest
          name: taiga-front
          resources: {}
      restartPolicy: Always
status: {}
