apiVersion: v1
kind: Service
metadata:
  namespace: taiga
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-db
  name: taiga-db
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: taiga-db
