apiVersion: v1
kind: Service
metadata:
  namespace: taiga
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-front
  name: taiga-front
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: taiga-front
