apiVersion: v1
kind: Service
metadata:
  namespace: taiga
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-protected
  name: taiga-protected
spec:
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  selector:
    io.kompose.service: taiga-protected
