apiVersion: v1
kind: Service
metadata:
  namespace: taiga
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-events
  name: taiga-events
spec:
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: taiga-events
