apiVersion: v1
kind: Service
metadata:
  namespace: taiga
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: taiga-events-rabbitmq
  name: taiga-events-rabbitmq
spec:
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
  selector:
    io.kompose.service: taiga-events-rabbitmq
